export const MEMBER_COSTWEI_PER_YEAR = '98000000000000000000';
export const RECHARGE_YEAR_TYPE = 1; // 按年充值
export const DEFAULT_GAS_LIMIT = 210000;
export const MIN_GAS_LIMIT = 21000;
export const DEFAULT_GAS_PRICE = 50000000000;
export const TX_PENDING = 'pending';
export const TX_FAILED = 'failed';
export const TX_CONFIRMED = 'confirmed';
export const DEFAULT_GAS_STATION_URL = 'https://ethgasstation.info/api/ethgasAPI.json';
