export const UPDATE_WEB_ITEMS = 'UPDATE_WEB_ITEMS';
export const UPDATE_WEBPLAIN = 'UPDATE_WEBPLAIN';
export const UPDATE_MOB_ITEMS = 'UPDATE_MOB_ITEMS';
export const UPDATE_MOBPLAIN = 'UPDATE_MOBPLAIN';
export const SET_TRANFER_ITEM = 'SET_TRANFER_ITEM';
