export const UPDATE_CHAINID = 'UPDATE_CHAINID';
export const UPDATE_SELECTED_ADDRESS = 'UPDATE_SELECTED_ADDRESS';
export const UPDATE_NETWORK_LIST = 'UPDATE_NETWORK_LIST';
export const UPDATE_CHAIN_BALANCES = 'UPDATE_CHAIN_BALANCES';
export const UPDATE_CHAIN_STATUS = 'UPDATE_CHAIN_STATUS';
export const UPDATE_GAS_STATE = 'UPDATE_GAS_STATE';
export const UPDATE_LASTTIMESATMP = 'UPDATE_LASTTIMESATMP';
