export const UPDATE_ITEMS = 'UPDATE_ITEMS';
export const UPDATE_FEILD_VOLUME = 'UPDATE_FEILD_VOLUME';
export const UPDATE_IS_UNLOCKED = 'UPDATE_IS_UNLOCKED';
export const UPDATE_HOSTNAME = 'UPDATE_HOSTNAME';
export const SET_VIEW_PATH = 'SET_VIEW_PATH';
export const UPDATE_ACTIVED_VALT_STATE = 'UPDATE_ACTIVED_VALT_STATE';
