export const UPDATE_P3_DRAWER = 'UPDATE_P3_DRAWER';
export const UPDATE_P3_DENSE = 'UPDATE_P3_DENSE';
export const UPDATE_SNACKBAR_STATE = 'UPDATE_SNACKBAR_STATE';
export const UPDATE_SNACKBAR_TEXT = 'UPDATE_SNACKBAR_TEXT';
export const UPDATE_SNACKBAR_TEXT_COLOR = 'UPDATE_SNACKBAR_TEXT_COLOR';
